wandb_version: 1

epochs:
  desc: null
  value: 1000
lr:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 16
acc_req:
  desc: null
  value: 0.95
run_val_every:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699591983.365829
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
